/* global */
// ================================================================
// Chariot — product catalog (real imagery + real pricing)
// Source: everything-chariot/website_pulls/{1nri,jireh}/manifest.md
// GHS → USD at 1 GHS ≈ $0.065 (rounded to whole USD, landed)
// ================================================================

const PRODUCTS = [
  // ───────────── 1NRI ─────────────
  { id:"nri-olive-grove",  brand:"1nri", name:"Olive Grove Jersey",        colorway:"Blue",        category:"Tops",        gh:300, us:62, status:"available",
    img:"assets/1nri/olive-grove-jersey-blue-01.jpg",
    images:["assets/1nri/olive-grove-jersey-blue-01.jpg","assets/1nri/olive-grove-jersey-blue-02.jpg"],
    desc:"Heavy mesh jersey knit. Embroidered crest on chest, oversized number on back. Oversized fit." },
  { id:"nri-varsity",      brand:"1nri", name:"Varsity Jersey 2.0",        colorway:"Ivory / Forest", category:"Tops",     gh:400, us:88, status:"available",
    img:"assets/1nri/varsity-jersey-01.jpg",
    images:["assets/1nri/varsity-jersey-01.jpg","assets/1nri/varsity-jersey-02.jpg"],
    desc:"Two-tone varsity half-zip. Sleeve patch, mixed-badge embroidery." },
  { id:"nri-life-death-b", brand:"1nri", name:"Life and Death Tee",        colorway:"Burgundy",    category:"Tops",        gh:320, us:68, status:"available",
    img:"assets/1nri/life-and-death-burgundy-01.jpg",
    images:["assets/1nri/life-and-death-burgundy-01.jpg","assets/1nri/life-and-death-burgundy-02.jpg"],
    desc:"Garment-dyed heavyweight cotton. Back-body puff print, cropped body." },
  { id:"nri-acid-red",     brand:"1nri", name:"Acid-Washed Shorts",        colorway:"Red",         category:"Bottoms",     gh:270, us:58, status:"available",
    img:"assets/1nri/acid-washed-shorts-red-01.jpg",
    images:["assets/1nri/acid-washed-shorts-red-01.jpg","assets/1nri/acid-washed-shorts-red-02.jpg"],
    desc:"Acid-washed heavyweight cotton shorts. Contrast drawstring, rear 1NRI embroidery." },
  { id:"nri-flare",        brand:"1nri", name:"Flare Sweatpants",          colorway:"Khaki",       category:"Bottoms",     gh:350, us:74, status:"available",
    img:"assets/1nri/flare-sweatpants-khaki-01.jpg",
    images:["assets/1nri/flare-sweatpants-khaki-01.jpg","assets/1nri/flare-sweatpants-khaki-02.jpg"],
    desc:"Brushed-back fleece. Elasticated waist, flared leg opening, tonal embroidery at thigh." },
  { id:"nri-sweat-shorts", brand:"1nri", name:"Sweat Shorts",              colorway:"Black",       category:"Bottoms",     gh:270, us:58, status:"available",
    img:"assets/1nri/sweat-shorts-black-01.jpg",
    images:["assets/1nri/sweat-shorts-black-01.jpg"],
    desc:"10-inch inseam brushed fleece shorts. Tonal embroidery, side-seam pockets." },
  { id:"nri-distressed",   brand:"1nri", name:"Distressed Caps",           colorway:"Washed",      category:"Accessories", gh:150, us:32, status:"available",
    img:"assets/1nri/distressed-caps-01.jpg",
    images:["assets/1nri/distressed-caps-01.jpg","assets/1nri/distressed-caps-02.jpg"],
    desc:"Washed and distressed 6-panel dad cap. Tonal laurel embroidery, adjustable strap." },
  { id:"nri-zion",         brand:"1nri", name:"Zion Airways",              colorway:"Black",       category:"Tops",        gh:350, us:74, status:"available",
    img:"assets/1nri/zion-airways-black-01.jpg",
    images:["assets/1nri/zion-airways-black-01.jpg","assets/1nri/zion-airways-black-02.jpg"],
    desc:"Graphic-heavy crewneck. Front chest embroidery, screen-printed airways back graphic." },
  { id:"nri-fur-black",    brand:"1nri", name:"Intercessory Dept. Fur Tee",colorway:"Black",       category:"Tops",        gh:300, us:62, status:"available",
    img:"assets/1nri/intercessory-fur-black-01.jpg",
    images:["assets/1nri/intercessory-fur-black-01.jpg"],
    desc:"Heavyweight tee with applied fur lettering. Boxy fit." },
  { id:"nri-fur",          brand:"1nri", name:"Intercessory Dept. Fur Tee",colorway:"Cream",       category:"Tops",        gh:300, us:62, status:"available",
    img:"assets/1nri/intercessory-fur-01.jpg",
    images:["assets/1nri/intercessory-fur-01.jpg"],
    desc:"Heavyweight tee with applied fur lettering. Boxy fit." },
  { id:"nri-genesis",      brand:"1nri", name:"Genesis Basic Top",         colorway:"Cream",       category:"Tops",        gh:200, us:42, status:"available",
    img:"assets/1nri/genesis-basic-top-01.jpg",
    images:["assets/1nri/genesis-basic-top-01.jpg","assets/1nri/genesis-basic-top-02.jpg"],
    desc:"Foundational tee in heavyweight cotton. Minimal chest mark." },

  // Sold out — shown as archive per brief ("remain visible, drives FOMO, proves demand")
  { id:"nri-sackcloth-clay",brand:"1nri", name:"Sackcloth Tee",            colorway:"Clay",        category:"Tops",        gh:400, us:88, status:"soldout",
    img:"assets/1nri/sackcloth-clay-01.jpg",
    images:["assets/1nri/sackcloth-clay-01.jpg","assets/1nri/sackcloth-clay-02.jpg"],
    desc:"Heavyweight tee, raw cut hems, tonal laurel embroidery at chest." },
  { id:"nri-sackcloth-obs",brand:"1nri",  name:"Sackcloth Tee",            colorway:"Obsidian",    category:"Tops",        gh:350, us:74, status:"soldout",
    img:"assets/1nri/sackcloth-obsidian-01.jpg",
    images:["assets/1nri/sackcloth-obsidian-01.jpg"],
    desc:"Heavyweight tee, raw cut hems, tonal laurel embroidery at chest." },
  { id:"nri-qzip",         brand:"1nri",  name:"Quarter-Zip",              colorway:"Black",       category:"Outerwear",   gh:350, us:74, status:"soldout",
    img:"assets/1nri/quarter-zip-black-01.jpg",
    images:["assets/1nri/quarter-zip-black-01.jpg","assets/1nri/quarter-zip-black-02.jpg"],
    desc:"Technical quarter-zip with chest pockets. Mandarin collar, two-way zip." },
  { id:"nri-dusk-button",  brand:"1nri",  name:"Dusk Before Dawn Button-Up",colorway:"Washed",     category:"Outerwear",   gh:320, us:68, status:"soldout",
    img:"assets/1nri/dusk-button-up-01.jpg",
    images:["assets/1nri/dusk-button-up-01.jpg","assets/1nri/dusk-button-up-02.jpg"],
    desc:"Cotton button-up with contrast cover-stitching. Boxy fit." },
  { id:"nri-dusk-black",   brand:"1nri",  name:"Dusk Before Dawn Tee",     colorway:"Black",       category:"Tops",        gh:250, us:54, status:"soldout",
    img:"assets/1nri/dusk-tee-black-01.jpg",
    images:["assets/1nri/dusk-tee-black-01.jpg"],
    desc:"Midweight jersey tee. Chest script + laurel crest." },
  { id:"nri-dusk-pink",    brand:"1nri",  name:"Dusk Before Dawn Tee",     colorway:"Pink",        category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/dusk-tee-pink-01.jpg",
    images:["assets/1nri/dusk-tee-pink-01.jpg","assets/1nri/dusk-tee-pink-02.jpg"],
    desc:"Midweight jersey tee. Chest script + laurel crest." },
  { id:"nri-dry-white",    brand:"1nri",  name:"Dry Bones Tee",            colorway:"White",       category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/dry-bones-tee-white-01.jpg",
    images:["assets/1nri/dry-bones-tee-white-01.jpg","assets/1nri/dry-bones-tee-white-02.jpg"],
    desc:"Heavyweight cotton tee. Dry Bones scripture graphic back print." },
  { id:"nri-dry-brown",    brand:"1nri",  name:"Dry Bones Coffee",         colorway:"Brown",       category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/dry-bones-coffee-brown-01.jpg",
    images:["assets/1nri/dry-bones-coffee-brown-01.jpg"],
    desc:"Garment-dyed heavyweight cotton tee." },
  { id:"nri-follow",       brand:"1nri",  name:"Follow God Coffee",        colorway:"Brown",       category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/follow-god-coffee-brown-01.jpg",
    images:["assets/1nri/follow-god-coffee-brown-01.jpg"],
    desc:"Garment-dyed heavyweight cotton tee." },
  { id:"nri-maison",       brand:"1nri",  name:"Maison de Prière",         colorway:"Cyan Blue",   category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/maison-cyan-01.jpg",
    images:["assets/1nri/maison-cyan-01.jpg"],
    desc:"Jersey knit, contrast piping at hem and sleeve. Chain-stitch wordmark." },
  { id:"nri-divine",       brand:"1nri",  name:"Divine Provision Tee",     colorway:"Washed",      category:"Tops",        gh:320, us:68, status:"soldout",
    img:"assets/1nri/divine-provision-tee-01.jpg",
    images:["assets/1nri/divine-provision-tee-01.jpg","assets/1nri/divine-provision-tee-02.jpg"],
    desc:"Graphic heavyweight tee, boxy fit, large back print." },
  { id:"nri-life-death",   brand:"1nri",  name:"Life and Death Tee",       colorway:"Cream",       category:"Tops",        gh:350, us:74, status:"soldout",
    img:"assets/1nri/life-and-death-tee-01.jpg",
    images:["assets/1nri/life-and-death-tee-01.jpg"],
    desc:"Garment-dyed heavyweight cotton. Back-body puff print." },
  { id:"nri-intercessory", brand:"1nri",  name:"Intercessory Dept Acid-Wash Tee", colorway:"Washed", category:"Tops",      gh:300, us:62, status:"soldout",
    img:"assets/1nri/intercessory-acid-wash-01.jpg",
    images:["assets/1nri/intercessory-acid-wash-01.jpg"],
    desc:"Acid-washed heavyweight tee. Department logo embroidery." },
  { id:"nri-time-chance",  brand:"1nri",  name:"Time & Chance SS25",       colorway:"Acid Wash",   category:"Tops",        gh:350, us:74, status:"soldout",
    img:"assets/1nri/time-chance-ss25-01.jpg",
    images:["assets/1nri/time-chance-ss25-01.jpg"],
    desc:"Seasonal acid-wash heavyweight tee." },
  { id:"nri-tishbe",       brand:"1nri",  name:"Tishbe Motors Tee",        colorway:"Washed",      category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/tishbe-motors-tee-01.jpg",
    images:["assets/1nri/tishbe-motors-tee-01.jpg"],
    desc:"Jersey-knit tee, motor-inspired embroidery." },
  { id:"nri-manger",       brand:"1nri",  name:"Manger Hotel",             colorway:"Natural",     category:"Tops",        gh:300, us:62, status:"soldout",
    img:"assets/1nri/manger-hotel-01.jpg",
    images:["assets/1nri/manger-hotel-01.jpg"],
    desc:"Heavyweight rugby knit. Screen-printed banner across chest." },
  { id:"nri-damaris",      brand:"1nri",  name:"Damaris Bag",              colorway:"Natural",     category:"Accessories", gh:270, us:58, status:"soldout",
    img:"assets/1nri/damaris-bag-01.jpg",
    images:["assets/1nri/damaris-bag-01.jpg","assets/1nri/damaris-bag-02.jpg"],
    desc:"Woven carry bag. Reinforced base, cotton strap, tonal label." },
  { id:"nri-acid-grey",    brand:"1nri",  name:"Acid Wash Shorts",         colorway:"Grey",        category:"Bottoms",     gh:270, us:58, status:"soldout",
    img:"assets/1nri/acid-wash-shorts-grey-01.jpg",
    images:["assets/1nri/acid-wash-shorts-grey-01.jpg"],
    desc:"Acid-washed heavyweight cotton shorts." },

  // ───────────── JIREH — Battle Angel collection ─────────────
  { id:"jir-ba-black-grey",    brand:"jireh", name:"Battle Angel Jersey", colorway:"Black / Grey",   category:"Tops", gh:340, us:72, status:"available",
    img:"assets/jireh/battle-angel-black-grey.jpg",
    images:["assets/jireh/battle-angel-black-grey.jpg","assets/jireh/campaign-01.jpg","assets/jireh/campaign-02.jpg"],
    desc:"Graphic jacquard knit. Front panel graphic, tipped sleeve, relaxed fit." },
  { id:"jir-ba-orange-grey",   brand:"jireh", name:"Battle Angel Jersey", colorway:"Orange / Grey",  category:"Tops", gh:340, us:72, status:"available",
    img:"assets/jireh/battle-angel-orange-grey.jpg",
    images:["assets/jireh/battle-angel-orange-grey.jpg","assets/jireh/campaign-03.jpg","assets/jireh/campaign-04.jpg"],
    desc:"Graphic jacquard knit. Front panel graphic, tipped sleeve, relaxed fit." },
  { id:"jir-ba-blue-white",    brand:"jireh", name:"Battle Angel Jersey", colorway:"Blue / White",   category:"Tops", gh:340, us:72, status:"available",
    img:"assets/jireh/battle-angel-blue-white.jpg",
    images:["assets/jireh/battle-angel-blue-white.jpg","assets/jireh/campaign-05.jpg","assets/jireh/campaign-06.jpg"],
    desc:"Graphic jacquard knit. Front panel graphic, tipped sleeve, relaxed fit." },
  { id:"jir-ba-black-yellow",  brand:"jireh", name:"Battle Angel Jersey", colorway:"Black / Yellow", category:"Tops", gh:340, us:72, status:"available",
    img:"assets/jireh/battle-angel-black-yellow.jpg",
    images:["assets/jireh/battle-angel-black-yellow.jpg","assets/jireh/campaign-07.jpg","assets/jireh/campaign-08.jpg"],
    desc:"Graphic jacquard knit. Front panel graphic, tipped sleeve, relaxed fit." }
];

const BRANDS = {
  "1nri": {
    slug: "1nri", name: "1NRI", city: "Accra, Ghana", since: "2021",
    tag: "An independent fashion label from Accra building a visual language around faith, purpose, and craft.",
    desc: "Each piece carries a name. Every collection is a statement. Now available in the US through Chariot.",
    source: "https://1nri.store/",
    cover: "assets/1nri/maison-cyan-01.jpg",
    portrait: "assets/1nri/manger-hotel-01.jpg"
  },
  "jireh": {
    slug: "jireh", name: "Jireh", city: "Accra, Ghana", since: "2023",
    tag: "A sportswear label from Accra with a design vocabulary rooted in precision and movement.",
    desc: "The Battle Angel collection is their statement piece. Now available in the US through Chariot.",
    source: "https://wearjireh.shop/",
    cover: "assets/jireh/campaign-02.jpg",
    portrait: "assets/jireh/campaign-04.jpg"
  }
};

const SHOP_SEGMENTS = [
  { key: "all",         label: "All" },
  { key: "1nri",        label: "1NRI" },
  { key: "jireh",       label: "Jireh" },
  { key: "available",   label: "Available" },
  { key: "Tops",        label: "Tops" },
  { key: "Outerwear",   label: "Outerwear" },
  { key: "Bottoms",     label: "Bottoms" },
  { key: "Accessories", label: "Accessories" },
  { key: "soldout",     label: "Sold Out Archive" }
];

Object.assign(window, { PRODUCTS, BRANDS, SHOP_SEGMENTS });
